import {Assets, Strings} from '../res/index';
/**
 * @description:This is string file
 * @author:Vibhishan
 * @created_on:18/05/2021
 * @param:Payload(data)
 * @return:
 * @modified_by:Vibhishan
 * @modified_on:23/07/2021
 */

export default {
  engageInYour: 'Engage in Your Financial Freedom.',
  loading: 'Loading...',
  welcome: 'Welcome',
  loginViaMobileNo: 'Sign in with mobile number',
  signupViaMobileNo: 'Sign up with mobile number',
  countryCode: '+01 - ',
  viewAll: 'View All',
  underDevlopment: 'Under Development',

  //OnBoarding
  onBoarding: {
    skip: 'Skip',
    onBoardingData: [
      {
        title1: 'Create and',
        title2: 'Manage a Funds',
        title3: 'Distribution Group',
        descreption1:'Anyone can create and manage a rotational',
        descreption2:'funds distribution group. Start for free',
        img: Assets.onboarding.first,
      },
      {
        title1: 'Receive Invitation',
        title2: 'and Join a Funds',
        title3: 'Distribution Group',
        descreption1:'Accept an invitation from your acquaintances to',
        descreption2:'join a rotational funds distribution group. Start for free',
        img: Assets.onboarding.second,
      },
      {
        title1: 'Create a Group to',
        title2: 'Raise Funds for',
        title3: 'Your Events',
        descreption1:'Send requests to raise funds',
        descreption2:'for your events',
        img: Assets.onboarding.third,
      },
      {
        title1: 'Set Reminders for',
        title2: 'Sending and',
        title3: 'Receiving Your Funds',
        descreption1:'Wealth Concert will remind members of',
        descreption2:'due dates to send or receive payments in time',
        img: Assets.onboarding.fourth,
      },
    ],
  },
  login: {
    welcome: 'Welcome!',
    enterEmailNPassword:
      'Please sign in to your account',
    firstNameMustNotBeEmpty: 'First name is a required field.',
    lastNameMustNotBeEmpty: 'Last name is a required field.',
    emailAddress: 'Email Address',
    enterYourEmailAddress: 'Enter your email address',
    enterYourRegisteredEmailAddress: 'Enter your registered email address',
    pleaseEnterAValidEmail: 'Please enter a valid email address.',
    emailShouldNotBeEmpty: 'Email address is a required field.',
    mobileNoShouldNotBeEmpty: 'Mobile number is a required field.',
    mobileNotValid: 'The mobile number you entered is not valid.',
    bankNotValid: 'Bank name is a required field.',
    bankingIdNotValid: 'Banking ID is a required field.',
    bankAccountNameNotValid: 'Bank account name is a required field.',
    pleaseEnterAValidPassword:
      'Password must be between 8-16 characters. Password must include both uppercase and lowercase characters (e.g., a-z and A-Z), at least one number (e.g., 0-9), and one special character (e.g., @#$%&*).',
    newPasswordNConfirmPasswordSame:
      'Passwords do not match.',
    pleaseEnterConfirmPassword: 'Please confirm your password.',  
    passwordNConfirmPasswordSame:
      'Passwords do not match.',
    forgotPassword: 'Forgot Password?',
    donotHaveAccount: `Don't have an account?`,
    register: 'Register',
    byContinue: 'By continuing, you agree to our',
    termsNConditions: 'Terms & Conditions',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    login: 'Sign in',
  },
  signup: {
    signup: 'Sign up',
    createAccount: 'Create New Account',
    pleaseFillTheForm: 'Please enter your information below to create a new account.',
    firstNameWithStar: 'First Name*',
    firstName: 'First Name',
    enterYourFirstName: 'Enter your first name',
    lastNameWithStart: 'Last Name*',
    lastName: 'Last Name',
    enterYourLastName: 'Enter your last name',
    emailAddressWithStar: 'Email Address*',
    mobileNumberWithStar: 'Mobile Number*',
    mobileNumber: 'Mobile Number',
    enterYourMobileNumber: 'Enter your mobile number',
    bankNameWithStar: 'Bank/App Name*',
    bankName: 'Bank/App Name',
    bankAccountWithStar: 'Bank Account*',
    bankAppNameWithStartNQMark: 'Bank/App Name*   ?',
    enterYourBankAppName: 'Enter your bank/app name',
    bankingAppIdWithStarNQMark: 'Banking #/App ID*   ?',
    bankAccountNumber: 'Bank Account Number*',
    enterBankAccountNumber: 'Enter bank account number',
    bankingAppId: 'Banking#/App ID',
    enterYourBankAppId: 'Enter your bank/app ID',
    bankAccountName: 'Bank Account Name*',
    enterYourBankAccountName: 'Enter your bank account name',
    iAccept: 'I accept the',
    termsAndConditions: 'Terms & Conditions',
    andIcon: 'and',
    alreadyHaveAnAccount: 'Already have an account?',
    password: 'Password',
    enterYourPassword: 'Enter your password',
    confirmPassword: 'Confirm Password',
    enterYourConfirmPassword: 'Confirm your password',
    selcetCountryCode: 'Select country code',
    countryId: {
      countryCodeData: 
     

      [
        {"id":"1","countryName":"Afghanistan","countryCode":"+93","currency":"AFN","countryFlag":"🇦🇫"},
        {"id":"2","countryName":"Aland Islands","countryCode":"+358-18","currency":"EUR","countryFlag":"🇦🇽"},
        {"id":"3","countryName":"Albania","countryCode":"+355","currency":"ALL","countryFlag":"🇦🇱"},
        {"id":"4","countryName":"Algeria","countryCode":"+213","currency":"DZD","countryFlag":"🇩🇿"},
        {"id":"5","countryName":"American Samoa","countryCode":"+1-684","currency":"USD","countryFlag":"🇦🇸"},
        {"id":"6","countryName":"Andorra","countryCode":"+376","currency":"EUR","countryFlag":"🇦🇩"},
        {"id":"7","countryName":"Angola","countryCode":"+244","currency":"AOA","countryFlag":"🇦🇴"},
        {"id":"8","countryName":"Anguilla","countryCode":"+1-264","currency":"XCD","countryFlag":"🇦🇮"},
        {"id":"9","countryName":"Antarctica","countryCode":"+672","currency":"AAD","countryFlag":"🇦🇶"},
        {"id":"10","countryName":"Antigua and Barbuda","countryCode":"+1-268","currency":"XCD","countryFlag":"🇦🇬"},
        {"id":"11","countryName":"Argentina","countryCode":"+54","currency":"ARS","countryFlag":"🇦🇷"},
        {"id":"12","countryName":"Armenia","countryCode":"+374","currency":"AMD","countryFlag":"🇦🇲"},
        {"id":"13","countryName":"Aruba","countryCode":"+297","currency":"AWG","countryFlag":"🇦🇼"},
        {"id":"14","countryName":"Australia","countryCode":"+61","currency":"AUD","countryFlag":"🇦🇺"},
        {"id":"15","countryName":"Austria","countryCode":"+43","currency":"EUR","countryFlag":"🇦🇹"},
        {"id":"16","countryName":"Azerbaijan","countryCode":"+994","currency":"AZN","countryFlag":"🇦🇿"},
        {"id":"17","countryName":"Bahamas","countryCode":"+1-242","currency":"BSD","countryFlag":"🇧🇸"},
        {"id":"18","countryName":"Bahrain","countryCode":"+973","currency":"BHD","countryFlag":"🇧🇭"},
        {"id":"19","countryName":"Bangladesh","countryCode":"+880","currency":"BDT","countryFlag":"🇧🇩"},
        {"id":"20","countryName":"Barbados","countryCode":"+1-246","currency":"BBD","countryFlag":"🇧🇧"},
        {"id":"21","countryName":"Belarus","countryCode":"+375","currency":"BYN","countryFlag":"🇧🇾"},
        {"id":"22","countryName":"Belgium","countryCode":"+32","currency":"EUR","countryFlag":"🇧🇪"},
        {"id":"23","countryName":"Belize","countryCode":"+501","currency":"BZD","countryFlag":"🇧🇿"},
        {"id":"24","countryName":"Benin","countryCode":"+229","currency":"XOF","countryFlag":"🇧🇯"},
        {"id":"25","countryName":"Bermuda","countryCode":"+1-441","currency":"BMD","countryFlag":"🇧🇲"},
        {"id":"26","countryName":"Bhutan","countryCode":"+975","currency":"BTN","countryFlag":"🇧🇹"},
        {"id":"27","countryName":"Bolivia","countryCode":"+591","currency":"BOB","countryFlag":"🇧🇴"},
        {"id":"28","countryName":"Bosnia and Herzegovina","countryCode":"+387","currency":"BAM","countryFlag":"🇧🇦"},
        {"id":"29","countryName":"Botswana","countryCode":"+267","currency":"BWP","countryFlag":"🇧🇼"},
        {"id":"30","countryName":"Bouvet Island","countryCode":"+47","currency":"NOK","countryFlag":"🇧🇻"},
        {"id":"31","countryName":"Brazil","countryCode":"+55","currency":"BRL","countryFlag":"🇧🇷"},
        {"id":"32","countryName":"British Indian Ocean Territory","countryCode":"+246","currency":"USD","countryFlag":"🇮🇴"},
        {"id":"33","countryName":"Brunei","countryCode":"+673","currency":"BND","countryFlag":"🇧🇳"},
        {"id":"34","countryName":"Bulgaria","countryCode":"+359","currency":"BGN","countryFlag":"🇧🇬"},
        {"id":"35","countryName":"Burkina Faso","countryCode":"+226","currency":"XOF","countryFlag":"🇧🇫"},
        {"id":"36","countryName":"Burundi","countryCode":"+257","currency":"BIF","countryFlag":"🇧🇮"},
        {"id":"37","countryName":"Cambodia","countryCode":"+855","currency":"KHR","countryFlag":"🇰🇭"},
        {"id":"38","countryName":"Cameroon","countryCode":"+237","currency":"XAF","countryFlag":"🇨🇲"},
        {"id":"39","countryName":"Canada","countryCode":"+1","currency":"CAD","countryFlag":"🇨🇦"},
        {"id":"40","countryName":"Cape Verde","countryCode":"+238","currency":"CVE","countryFlag":"🇨🇻"},
        {"id":"41","countryName":"Cayman Islands","countryCode":"+1-345","currency":"KYD","countryFlag":"🇰🇾"},
        {"id":"42","countryName":"Central African Republic","countryCode":"+236","currency":"XAF","countryFlag":"🇨🇫"},
        {"id":"43","countryName":"Chad","countryCode":"+235","currency":"XAF","countryFlag":"🇹🇩"},
        {"id":"44","countryName":"Chile","countryCode":"+56","currency":"CLP","countryFlag":"🇨🇱"},
        {"id":"45","countryName":"China","countryCode":"+86","currency":"CNY","countryFlag":"🇨🇳"},
        {"id":"46","countryName":"Christmas Island","countryCode":"+61","currency":"AUD","countryFlag":"🇨🇽"},
        {"id":"47","countryName":"Cocos (Keeling) Islands","countryCode":"+61","currency":"AUD","countryFlag":"🇨🇨"},
        {"id":"48","countryName":"Colombia","countryCode":"+57","currency":"COP","countryFlag":"🇨🇴"},
        {"id":"49","countryName":"Comoros","countryCode":"+269","currency":"KMF","countryFlag":"🇰🇲"},
        {"id":"50","countryName":"Congo","countryCode":"+242","currency":"XAF","countryFlag":"🇨🇬"},
        {"id":"51","countryName":"The Democratic Republic of the Congo","countryCode":"+243","currency":"CDF","countryFlag":"🇨🇩"},
        {"id":"52","countryName":"Cook Islands","countryCode":"+682","currency":"NZD","countryFlag":"🇨🇰"},
        {"id":"53","countryName":"Costa Rica","countryCode":"+506","currency":"CRC","countryFlag":"🇨🇷"},
        {"id":"54","countryName":"Cote D'Ivoire (Ivory Coast)","countryCode":"+225","currency":"XOF","countryFlag":"🇨🇮"},
        {"id":"55","countryName":"Croatia (Hrvatska)","countryCode":"+385","currency":"HRK","countryFlag":"🇭🇷"},
        {"id":"56","countryName":"Cuba","countryCode":"+53","currency":"CUP","countryFlag":"🇨🇺"},
        {"id":"57","countryName":"Cyprus","countryCode":"+357","currency":"EUR","countryFlag":"🇨🇾"},
        {"id":"58","countryName":"Czech Republic","countryCode":"+420","currency":"CZK","countryFlag":"🇨🇿"},
        {"id":"59","countryName":"Denmark","countryCode":"+45","currency":"DKK","countryFlag":"🇩🇰"},
        {"id":"60","countryName":"Djibouti","countryCode":"+253","currency":"DJF","countryFlag":"🇩🇯"},
        {"id":"61","countryName":"Dominica","countryCode":"+1-767","currency":"XCD","countryFlag":"🇩🇲"},
        {"id":"62","countryName":"Dominican Republic","countryCode":"+1-809","currency":"DOP","countryFlag":"🇩🇴"},
        {"id":"63","countryName":"East Timor","countryCode":"+670","currency":"USD","countryFlag":"🇹🇱"},
        {"id":"64","countryName":"Ecuador","countryCode":"+593","currency":"USD","countryFlag":"🇪🇨"},
        {"id":"65","countryName":"Egypt","countryCode":"+20","currency":"EGP","countryFlag":"🇪🇬"},
        {"id":"66","countryName":"El Salvador","countryCode":"+503","currency":"USD","countryFlag":"🇸🇻"},
        {"id":"67","countryName":"Equatorial Guinea","countryCode":"+240","currency":"XAF","countryFlag":"🇬🇶"},
        {"id":"68","countryName":"Eritrea","countryCode":"+291","currency":"ERN","countryFlag":"🇪🇷"},
        {"id":"69","countryName":"Estonia","countryCode":"+372","currency":"EUR","countryFlag":"🇪🇪"},
        {"id":"70","countryName":"Ethiopia","countryCode":"+251","currency":"ETB","countryFlag":"🇪🇹"},
        {"id":"71","countryName":"Falkland Islands","countryCode":"+500","currency":"FKP","countryFlag":"🇫🇰"},
        {"id":"72","countryName":"Faroe Islands","countryCode":"+298","currency":"DKK","countryFlag":"🇫🇴"},
        {"id":"73","countryName":"Fiji Islands","countryCode":"+679","currency":"FJD","countryFlag":"🇫🇯"},
        {"id":"74","countryName":"Finland","countryCode":"+358","currency":"EUR","countryFlag":"🇫🇮"},
        {"id":"75","countryName":"France","countryCode":"+33","currency":"EUR","countryFlag":"🇫🇷"},
        {"id":"76","countryName":"French Guiana","countryCode":"+594","currency":"EUR","countryFlag":"🇬🇫"},
        {"id":"77","countryName":"French Polynesia","countryCode":"+689","currency":"XPF","countryFlag":"🇵🇫"},
        {"id":"78","countryName":"French Southern Territories","countryCode":"+262","currency":"EUR","countryFlag":"🇹🇫"},
        {"id":"79","countryName":"Gabon","countryCode":"+241","currency":"XAF","countryFlag":"🇬🇦"},
        {"id":"80","countryName":"Gambia ","countryCode":"+220","currency":"GMD","countryFlag":"🇬🇲"},
        {"id":"81","countryName":"Georgia","countryCode":"+995","currency":"GEL","countryFlag":"🇬🇪"},
        {"id":"82","countryName":"Germany","countryCode":"+49","currency":"EUR","countryFlag":"🇩🇪"},
        {"id":"83","countryName":"Ghana","countryCode":"+233","currency":"GHS","countryFlag":"🇬🇭"},
        {"id":"84","countryName":"Gibraltar","countryCode":"+350","currency":"GIP","countryFlag":"🇬🇮"},
        {"id":"85","countryName":"Greece","countryCode":"+30","currency":"EUR","countryFlag":"🇬🇷"},
        {"id":"86","countryName":"Greenland","countryCode":"+299","currency":"DKK","countryFlag":"🇬🇱"},
        {"id":"87","countryName":"Grenada","countryCode":"+1-473","currency":"XCD","countryFlag":"🇬🇩"},
        {"id":"88","countryName":"Guadeloupe","countryCode":"+590","currency":"EUR","countryFlag":"🇬🇵"},
        {"id":"89","countryName":"Guam","countryCode":"+1-671","currency":"USD","countryFlag":"🇬🇺"},
        {"id":"90","countryName":"Guatemala","countryCode":"+502","currency":"GTQ","countryFlag":"🇬🇹"},
        {"id":"91","countryName":"Guernsey and Alderney","countryCode":"+44-1481","currency":"GBP","countryFlag":"🇬🇬"},
        {"id":"92","countryName":"Guinea","countryCode":"+224","currency":"GNF","countryFlag":"🇬🇳"},
        {"id":"93","countryName":"Guinea-Bissau","countryCode":"+245","currency":"XOF","countryFlag":"🇬🇼"},
        {"id":"94","countryName":"Guyana","countryCode":"+592","currency":"GYD","countryFlag":"🇬🇾"},
        {"id":"95","countryName":"Haiti","countryCode":"+509","currency":"HTG","countryFlag":"🇭🇹"},
        {"id":"96","countryName":"Heard and McDonald Islands","countryCode":"0","currency":"AUD","countryFlag":"🇭🇲"},
        {"id":"97","countryName":"Honduras","countryCode":"+504","currency":"HNL","countryFlag":"🇭🇳"},
        {"id":"98","countryName":"Hong Kong S.A.R.","countryCode":"+852","currency":"HKD","countryFlag":"🇭🇰"},
        {"id":"99","countryName":"Hungary","countryCode":"+36","currency":"HUF","countryFlag":"🇭🇺"},
        {"id":"100","countryName":"Iceland","countryCode":"+354","currency":"ISK","countryFlag":"🇮🇸"},
        {"id":"101","countryName":"India","countryCode":"+91","currency":"INR","countryFlag":"🇮🇳"},
        {"id":"102","countryName":"Indonesia","countryCode":"+62","currency":"IDR","countryFlag":"🇮🇩"},
        {"id":"103","countryName":"Iran","countryCode":"+98","currency":"IRR","countryFlag":"🇮🇷"},
        {"id":"104","countryName":"Iraq","countryCode":"+964","currency":"IQD","countryFlag":"🇮🇶"},
        {"id":"105","countryName":"Ireland","countryCode":"+353","currency":"EUR","countryFlag":"🇮🇪"},
        {"id":"106","countryName":"Israel","countryCode":"+972","currency":"ILS","countryFlag":"🇮🇱"},
        {"id":"107","countryName":"Italy","countryCode":"+39","currency":"EUR","countryFlag":"🇮🇹"},
        {"id":"108","countryName":"Jamaica","countryCode":"+1-876","currency":"JMD","countryFlag":"🇯🇲"},
        {"id":"109","countryName":"Japan","countryCode":"+81","currency":"JPY","countryFlag":"🇯🇵"},
        {"id":"110","countryName":"Jersey","countryCode":"+44-1534","currency":"GBP","countryFlag":"🇯🇪"},
        {"id":"111","countryName":"Jordan","countryCode":"+962","currency":"JOD","countryFlag":"🇯🇴"},
        {"id":"112","countryName":"Kazakhstan","countryCode":"+7","currency":"KZT","countryFlag":"🇰🇿"},
        {"id":"113","countryName":"Kenya","countryCode":"+254","currency":"KES","countryFlag":"🇰🇪"},
        {"id":"114","countryName":"Kiribati","countryCode":"+686","currency":"AUD","countryFlag":"🇰🇮"},
        {"id":"115","countryName":"Korea North","countryCode":"+850","currency":"KPW","countryFlag":"🇰🇵"},
        {"id":"116","countryName":"Korea South","countryCode":"+82","currency":"KRW","countryFlag":"🇰🇷"},
        {"id":"117","countryName":"Kuwait","countryCode":"+965","currency":"KWD","countryFlag":"🇰🇼"},
        {"id":"118","countryName":"Kyrgyzstan","countryCode":"+996","currency":"KGS","countryFlag":"🇰🇬"},
        {"id":"119","countryName":"Laos","countryCode":"+856","currency":"LAK","countryFlag":"🇱🇦"},
        {"id":"120","countryName":"Latvia","countryCode":"+371","currency":"EUR","countryFlag":"🇱🇻"},
        {"id":"121","countryName":"Lebanon","countryCode":"+961","currency":"LBP","countryFlag":"🇱🇧"},
        {"id":"122","countryName":"Lesotho","countryCode":"+266","currency":"LSL","countryFlag":"🇱🇸"},
        {"id":"123","countryName":"Liberia","countryCode":"+231","currency":"LRD","countryFlag":"🇱🇷"},
        {"id":"124","countryName":"Libya","countryCode":"+218","currency":"LYD","countryFlag":"🇱🇾"},
        {"id":"125","countryName":"Liechtenstein","countryCode":"+423","currency":"CHF","countryFlag":"🇱🇮"},
        {"id":"126","countryName":"Lithuania","countryCode":"+370","currency":"EUR","countryFlag":"🇱🇹"},
        {"id":"127","countryName":"Luxembourg","countryCode":"+352","currency":"EUR","countryFlag":"🇱🇺"},
        {"id":"128","countryName":"Macau S.A.R.","countryCode":"+853","currency":"MOP","countryFlag":"🇲🇴"},
        {"id":"129","countryName":"Macedonia","countryCode":"+389","currency":"MKD","countryFlag":"🇲🇰"},
        {"id":"130","countryName":"Madagascar","countryCode":"+261","currency":"MGA","countryFlag":"🇲🇬"},
        {"id":"131","countryName":"Malawi","countryCode":"+265","currency":"MWK","countryFlag":"🇲🇼"},
        {"id":"132","countryName":"Malaysia","countryCode":"+60","currency":"MYR","countryFlag":"🇲🇾"},
        {"id":"133","countryName":"Maldives","countryCode":"+960","currency":"MVR","countryFlag":"🇲🇻"},
        {"id":"134","countryName":"Mali","countryCode":"+223","currency":"XOF","countryFlag":"🇲🇱"},
        {"id":"135","countryName":"Malta","countryCode":"+356","currency":"EUR","countryFlag":"🇲🇹"},
        {"id":"136","countryName":"Isle of Man","countryCode":"+44-1624","currency":"GBP","countryFlag":"🇮🇲"},
        {"id":"137","countryName":"Marshall Islands","countryCode":"+692","currency":"USD","countryFlag":"🇲🇭"},
        {"id":"138","countryName":"Martinique","countryCode":"+596","currency":"EUR","countryFlag":"🇲🇶"},
        {"id":"139","countryName":"Mauritania","countryCode":"+222","currency":"MRO","countryFlag":"🇲🇷"},
        {"id":"140","countryName":"Mauritius","countryCode":"+230","currency":"MUR","countryFlag":"🇲🇺"},
        {"id":"141","countryName":"Mayotte","countryCode":"+262","currency":"EUR","countryFlag":"🇾🇹"},
        {"id":"142","countryName":"Mexico","countryCode":"+52","currency":"MXN","countryFlag":"🇲🇽"},
        {"id":"143","countryName":"Micronesia","countryCode":"+691","currency":"USD","countryFlag":"🇫🇲"},
        {"id":"144","countryName":"Moldova","countryCode":"+373","currency":"MDL","countryFlag":"🇲🇩"},
        {"id":"145","countryName":"Monaco","countryCode":"+377","currency":"EUR","countryFlag":"🇲🇨"},
        {"id":"146","countryName":"Mongolia","countryCode":"+976","currency":"MNT","countryFlag":"🇲🇳"},
        {"id":"147","countryName":"Montenegro","countryCode":"+382","currency":"EUR","countryFlag":"🇲🇪"},
        {"id":"148","countryName":"Montserrat","countryCode":"+1-664","currency":"XCD","countryFlag":"🇲🇸"},
        {"id":"149","countryName":"Morocco","countryCode":"+212","currency":"MAD","countryFlag":"🇲🇦"},
        {"id":"150","countryName":"Mozambique","countryCode":"+258","currency":"MZN","countryFlag":"🇲🇿"},
        {"id":"151","countryName":"Myanmar","countryCode":"+95","currency":"MMK","countryFlag":"🇲🇲"},
        {"id":"152","countryName":"Namibia","countryCode":"+264","currency":"NAD","countryFlag":"🇳🇦"},
        {"id":"153","countryName":"Nauru","countryCode":"+674","currency":"AUD","countryFlag":"🇳🇷"},
        {"id":"154","countryName":"Nepal","countryCode":"+977","currency":"NPR","countryFlag":"🇳🇵"},
        {"id":"155","countryName":"Netherlands Antilles","countryCode":"+599","currency":"ANG","countryFlag":"🇮🇸"},
        {"id":"156","countryName":"Netherlands ","countryCode":"+31","currency":"EUR","countryFlag":"🇳🇱"},
        {"id":"157","countryName":"New Caledonia","countryCode":"+687","currency":"XPF","countryFlag":"🇳🇨"},
        {"id":"158","countryName":"New Zealand","countryCode":"+64","currency":"NZD","countryFlag":"🇳🇿"},
        {"id":"159","countryName":"Nicaragua","countryCode":"+505","currency":"NIO","countryFlag":"🇳🇮"},
        {"id":"160","countryName":"Niger","countryCode":"+227","currency":"XOF","countryFlag":"🇳🇪"},
        {"id":"161","countryName":"Nigeria","countryCode":"+234","currency":"NGN","countryFlag":"🇳🇬"},
        {"id":"162","countryName":"Niue","countryCode":"+683","currency":"NZD","countryFlag":"🇳🇺"},
        {"id":"163","countryName":"Norfolk Island","countryCode":"+672","currency":"AUD","countryFlag":"🇳🇫"},
        {"id":"164","countryName":"Northern Mariana Islands","countryCode":"+1-670","currency":"USD","countryFlag":"🇲🇵"},
        {"id":"165","countryName":"Norway","countryCode":"+47","currency":"NOK","countryFlag":"🇳🇴"},
        {"id":"166","countryName":"Oman","countryCode":"+968","currency":"OMR","countryFlag":"🇴🇲"},
        {"id":"167","countryName":"Pakistan","countryCode":"+92","currency":"PKR","countryFlag":"🇵🇰"},
        {"id":"168","countryName":"Palau","countryCode":"+680","currency":"USD","countryFlag":"🇵🇼"},
        {"id":"169","countryName":"Palestinian Territory Occupied","countryCode":"+970","currency":"ILS","countryFlag":"🇵🇸"},
        {"id":"170","countryName":"Panama","countryCode":"+507","currency":"PAB","countryFlag":"🇵🇦"},
        {"id":"171","countryName":"Papua New Guinea","countryCode":"+675","currency":"PGK","countryFlag":"🇵🇬"},
        {"id":"172","countryName":"Paraguay","countryCode":"+595","currency":"PYG","countryFlag":"🇵🇾"},
        {"id":"173","countryName":"Peru","countryCode":"+51","currency":"PEN","countryFlag":"🇵🇪"},
        {"id":"174","countryName":"Philippines","countryCode":"+63","currency":"PHP","countryFlag":"🇵🇭"},
        {"id":"175","countryName":"Pitcairn Island","countryCode":"+870","currency":"NZD","countryFlag":"🇵🇳"},
        {"id":"176","countryName":"Poland","countryCode":"+48","currency":"PLN","countryFlag":"🇵🇱"},
        {"id":"177","countryName":"Portugal","countryCode":"+351","currency":"EUR","countryFlag":"🇵🇹"},
        {"id":"178","countryName":"Puerto Rico","countryCode":"+1-787","currency":"USD","countryFlag":"🇵🇷"},
        {"id":"179","countryName":"Qatar","countryCode":"+974","currency":"QAR","countryFlag":"🇶🇦"},
        {"id":"180","countryName":"Reunion","countryCode":"+262","currency":"EUR","countryFlag":"🇷🇪"},
        {"id":"181","countryName":"Romania","countryCode":"+40","currency":"RON","countryFlag":"🇷🇴"},
        {"id":"182","countryName":"Russia","countryCode":"+7","currency":"RUB","countryFlag":"🇷🇺"},
        {"id":"183","countryName":"Rwanda","countryCode":"+250","currency":"RWF","countryFlag":"🇷🇼"},
        {"id":"184","countryName":"Saint Helena","countryCode":"+290","currency":"SHP","countryFlag":"🇸🇭"},
        {"id":"185","countryName":"Saint Kitts and Nevis","countryCode":"+1-869","currency":"XCD","countryFlag":"🇰🇳"},
        {"id":"186","countryName":"Saint Lucia","countryCode":"+1-758","currency":"XCD","countryFlag":"🇱🇨"},
        {"id":"187","countryName":"Saint Pierre and Miquelon","countryCode":"+508","currency":"EUR","countryFlag":"🇵🇲"},
        {"id":"188","countryName":"Saint Vincent and the Grenadines","countryCode":"+1-784","currency":"XCD","countryFlag":"🇻🇨"},
        {"id":"189","countryName":"Saint-Barthelemy","countryCode":"+590","currency":"EUR","countryFlag":"🇧🇱"},
        {"id":"190","countryName":"Saint-Martin (French)","countryCode":"+590","currency":"EUR","countryFlag":"🇲🇫"},
        {"id":"191","countryName":"Samoa","countryCode":"+685","currency":"WST","countryFlag":"🇼🇸"},
        {"id":"192","countryName":"San Marino","countryCode":"+378","currency":"EUR","countryFlag":"🇸🇲"},
        {"id":"193","countryName":"Sao Tome and Principe","countryCode":"+239","currency":"STD","countryFlag":"🇸🇹"},
        {"id":"194","countryName":"Saudi Arabia","countryCode":"+966","currency":"SAR","countryFlag":"🇸🇦"},
        {"id":"195","countryName":"Senegal","countryCode":"+221","currency":"XOF","countryFlag":"🇸🇳"},
        {"id":"196","countryName":"Serbia","countryCode":"+381","currency":"RSD","countryFlag":"🇷🇸"},
        {"id":"197","countryName":"Seychelles","countryCode":"+248","currency":"SCR","countryFlag":"🇸🇨"},
        {"id":"198","countryName":"Sierra Leone","countryCode":"+232","currency":"SLL","countryFlag":"🇸🇱"},
        {"id":"199","countryName":"Singapore","countryCode":"+65","currency":"SGD","countryFlag":"🇸🇬"},
        {"id":"200","countryName":"Slovakia","countryCode":"+421","currency":"EUR","countryFlag":"🇸🇰"},
        {"id":"201","countryName":"Slovenia","countryCode":"+386","currency":"EUR","countryFlag":"🇸🇮"},
        {"id":"202","countryName":"Solomon Islands","countryCode":"+677","currency":"SBD","countryFlag":"🇸🇧"},
        {"id":"203","countryName":"Somalia","countryCode":"+252","currency":"SOS","countryFlag":"🇸🇴"},
        {"id":"204","countryName":"South Africa","countryCode":"+27","currency":"ZAR","countryFlag":"🇿🇦"},
        {"id":"205","countryName":"South Georgia","countryCode":"+500","currency":"GBP","countryFlag":"🇬🇸"},
        {"id":"206","countryName":"South Sudan","countryCode":"+211","currency":"SSP","countryFlag":"🇸🇸"},
        {"id":"207","countryName":"Spain","countryCode":"+34","currency":"EUR","countryFlag":"🇪🇸"},
        {"id":"208","countryName":"Sri Lanka","countryCode":"+94","currency":"LKR","countryFlag":"🇱🇰"},
        {"id":"209","countryName":"Sudan","countryCode":"+249","currency":"SDG","countryFlag":"🇸🇩"},
        {"id":"210","countryName":"Suriname","countryCode":"+597","currency":"SRD","countryFlag":"🇸🇷"},
        {"id":"211","countryName":"Svalbard and Jan Mayen Islands","countryCode":"+47","currency":"NOK","countryFlag":"🇸🇯"},
        {"id":"212","countryName":"Swaziland","countryCode":"+268","currency":"SZL","countryFlag":"🇸🇿"},
        {"id":"213","countryName":"Sweden","countryCode":"+46","currency":"SEK","countryFlag":"🇸🇪"},
        {"id":"214","countryName":"Switzerland","countryCode":"+41","currency":"CHF","countryFlag":"🇨🇭"},
        {"id":"215","countryName":"Syria","countryCode":"+963","currency":"SYP","countryFlag":"🇸🇾"},
        {"id":"216","countryName":"Taiwan","countryCode":"+886","currency":"TWD","countryFlag":"🇹🇼"},
        {"id":"217","countryName":"Tajikistan","countryCode":"+992","currency":"TJS","countryFlag":"🇹🇯"},
        {"id":"218","countryName":"Tanzania","countryCode":"+255","currency":"TZS","countryFlag":"🇹🇿"},
        {"id":"219","countryName":"Thailand","countryCode":"+66","currency":"THB","countryFlag":"🇹🇭"},
        {"id":"220","countryName":"Togo","countryCode":"+228","currency":"XOF","countryFlag":"🇹🇬"},
        {"id":"221","countryName":"Tokelau","countryCode":"+690","currency":"NZD","countryFlag":"🇹🇰"},
        {"id":"222","countryName":"Tonga","countryCode":"+676","currency":"TOP","countryFlag":"🇹🇴"},
        {"id":"223","countryName":"Trinidad and Tobago","countryCode":"+1-868","currency":"TTD","countryFlag":"🇹🇹"},
        {"id":"224","countryName":"Tunisia","countryCode":"+216","currency":"TND","countryFlag":"🇹🇳"},
        {"id":"225","countryName":"Turkey","countryCode":"+90","currency":"TRY","countryFlag":"🇹🇷"},
        {"id":"226","countryName":"Turkmenistan","countryCode":"+993","currency":"TMT","countryFlag":"🇹🇲"},
        {"id":"227","countryName":"Turks and Caicos Islands","countryCode":"+1-649","currency":"USD","countryFlag":"🇹🇨"},
        {"id":"228","countryName":"Tuvalu","countryCode":"+688","currency":"AUD","countryFlag":"🇹🇻"},
        {"id":"229","countryName":"Uganda","countryCode":"+256","currency":"UGX","countryFlag":"🇺🇬"},
        {"id":"230","countryName":"Ukraine","countryCode":"+380","currency":"UAH","countryFlag":"🇺🇦"},
        {"id":"231","countryName":"United Arab Emirates","countryCode":"+971","currency":"AED","countryFlag":"🇦🇪"},
        {"id":"232","countryName":"United Kingdom","countryCode":"+44","currency":"GBP","countryFlag":"🇬🇧"},
        {"id":"233","countryName":"United States","countryCode":"+1","currency":"USD","countryFlag":"🇺🇸"},
        {"id":"234","countryName":"United States Minor Outlying Islands","countryCode":"+1","currency":"USD","countryFlag":"🇺🇲"},
        {"id":"235","countryName":"Uruguay","countryCode":"+598","currency":"UYU","countryFlag":"🇺🇾"},
        {"id":"236","countryName":"Uzbekistan","countryCode":"+998","currency":"UZS","countryFlag":"🇺🇿"},
        {"id":"237","countryName":"Vanuatu","countryCode":"+678","currency":"VUV","countryFlag":"🇻🇺"},
        {"id":"238","countryName":"Vatican City State","countryCode":"+379","currency":"EUR","countryFlag":"🇻🇦"},
        {"id":"239","countryName":"Venezuela","countryCode":"+58","currency":"VEF","countryFlag":"🇻🇪"},
        {"id":"240","countryName":"Vietnam","countryCode":"+84","currency":"VND","countryFlag":"🇻🇳"},
        {"id":"241","countryName":"Virgin Islands (British)","countryCode":"+1-284","currency":"USD","countryFlag":"🇻🇬"},
        {"id":"242","countryName":"Virgin Islands (US)","countryCode":"+1-340","currency":"USD","countryFlag":"🇻🇮"},
        {"id":"243","countryName":"Wallis and Futuna Islands","countryCode":"+681","currency":"XPF","countryFlag":"🇼🇫"},
        {"id":"244","countryName":"Western Sahara","countryCode":"+212","currency":"MAD","countryFlag":"🇪🇭"},
        {"id":"245","countryName":"Yemen","countryCode":"+967","currency":"YER","countryFlag":"🇾🇪"},
        {"id":"246","countryName":"Zambia","countryCode":"+260","currency":"ZMW","countryFlag":"🇿🇲"},
        {"id":"247","countryName":"Zimbabwe","countryCode":"+263","currency":"ZWL","countryFlag":"🇿🇼"},
        {"id":"248","countryName":"Kosovo","countryCode":"+383","currency":"EUR","countryFlag":"🇽🇰"}
        ]    
  },
  },
  forgotPassword: {
    forgotPassword: 'Forgot Password',
    weWillSendAFourDigit:
      'We have sent a 4-digit  verification code to the registered email address, which will allow you to reset your password.',
    resetPassword: 'Reset Password',
    createNConfirm:
      'Create and confirm your new password below to access your account',
    newPassword: 'New Password',
  },
  otp: {
    verify: 'Verify',
    pleaseEnterTheFourDigit:
      'Please enter the 4-digit verification code, which we have sent to the registered email address.',
    cancel: 'Cancel',
    didNotRecieveOtp: 'Didn’t receive verification code?',
    resend: 'Resend',
  },
  verifyOtp: {
    verifyEmail: 'Verify Email',
    verifyMobile: 'Verify Mobile',
    pleaseEnterCodeToRegisteredEmail:
      'Please enter the 4-digit verification code, which we have sent to the registered email address.',
    pleaseEnterCodeToRegisteredMobile:
      'Please enter the 4-digit verification code, which we have sent to the registered mobile number.',
    cancel: 'Cancel',
    didNotRecieveOtp: 'Didn’t receive verification code?',
    resend: 'Resend',
    verifyNow: 'Verify Now'
  },
  sussessModel: {
    passwordChnaged: 'Password Changed!',
    youPasswordHasBeenChanged: 'Your password has been successfully changed.',
    Congratulations: 'Congratulations!',
    yourAccountHasbeenCreated: 'Your account has been successfully created.',
  },
  home: {
    fundGroups: 'Fund Groups',
    fundRaisingRequests: 'Fund Raising Requests',
    createA: 'Create a ',
    fundGroup: 'Fund Group',
    allGroup: 'All Groups ',
    groupInvitations: 'Group Invitations ',
    youHavenNotCreated: `You haven't created`,
    anyGroup: 'any group yet!',
    filter: {
      filter: 'Filter',
      reset: 'Reset',
      result: 'Result',
      selectFilter: 'Select Filter',
      filterByData: [
        {title: 'Groups Coordinated)'},
        {title: 'Groups Joined )'},
      ],
      createdByMe: 'created by me',
      invited: 'invited'
    },
    createFundGroup: {
      createFundGroup: 'Create Fund Group',
    },
    groupDetails: {
      groupDetailsTitle: 'Fund Group Details',
      groupStatus: 'Group Status',
      inActive: 'Inactive',
      active: 'Active',
      rejected: 'Rejected',
      groupDetailsCategoryData: [
        {
          title1: 'GROUP',
          title2: 'DETAILS'
        },
        {
          title1: 'HOW YOU ARE',
          title2: 'PAYING OTHERS',
        },
        {
          title1: 'HOW OTHERS',
          title2: 'ARE PAYING YOU'
        }
      ],
      filter: {
        filter: 'Filter'
      },
      coordinatorName: 'Coordinator Name',
      enterCoordinatorName: 'Enter coordinator name',
      removeGroup: 'Remove Group',
      activateTheGroup: 'Activate the Group',
      onceEveryMemberAcceptLine1: '*Once every member accepts the invitation, the coordinator',
      onceEveryMemberAcceptLine2: 'can change the member order.',
      
      onceAllMemberLine1: 'Once all members have accepted the group invitation,',
      onceAllMemberLine2: 'the coordinator can change the order before activating the group.',
      coordinatorCanRemoveLine1: 'Coordinator can remove and edit the group details',
      coordinatorCanRemoveLine2: 'before the group is activated.',
      beneficiaryNameNGroupAcceptenceStatus: 'Beneficiary Name and Member Acceptance Status',
      orderBeneficiaryName: 'Order* Beneficiary Name',
      groupAcceptenceStatus: 'Member Acceptance Status',
      setRandomOrder: 'Set Auto Random Order',
      accepted: 'Accepted',
      awaiting: 'Awaiting',
      groupEdited: 'Group Edited!',
      groupActivatedTitle: 'Final Confirmation to Activate the Group.',
      groupActivatedDescription: 'Are you sure you want to activate this group? Once the group is activated, you cannot change any details.',
      yourGroupHasBeenEditedSuccessfully: 'Your changes have been saved.',
      areYouSure: 'Wait…',
      wantToDeleteGroup: 'Removing this group cannot be undone. Are you sure?',
      wantToDeleteMember: 'Removing this member cannot be undone. Are you sure?',
      remove: 'Remove'
    },
    howYouNOthersPaying: {
       noAnyunpaidMember:'All members have paid.',
       currentPaymentDueBy: 'Current Payment Due By',
       enterCurrentPaymentDueBy: 'Enter the date by which the current payment is due',
       nextPaymentDueBy: 'Next Payment Due By',
       enterNextPaymentDueBy: 'Enter the date by which the next payment is due',
       currentBeneficiary: 'Current Beneficiary',
       enterCurrentBeneficiary: 'Enter the member who will receive the first funds distribution',
       nextBeneficiary: 'Next Beneficiary',
       enterNextBeneficiary: 'Enter the member who will receive the second funds distribution',
       yourContributionSoFar: 'Your contributions to date',
       enterYourContributions: 'Enter your contributions',
       contributionNo: 'Contribution Number',
       date: 'Date',
       status: 'Status',
       contribution: 'Contribution',
       orderNo: 'Order Number',
       beneficiaryName: 'Beneficiary Name',
       beneficiaryNameWithStar: 'Unpaid Member Name*',
       noDues: 'No Dues',
       legendPaymentStatus: 'Legend (Payment Status)',
       noPayment: 'No Payment',
       shortPayment: 'Short Payment',
       paymentInProcess: 'Payment in Progress ',
       confirmPayment: 'Confirm Sending Payment',
       missedPayment: 'Missed Payment',
       paymentCompleted: 'Payment Completed',
       setReminder: 'Set Reminder',
       contributionReceivedFromOthers : 'Contributions received from others',
       enterContributionReceivedFromOthers : 'Enter contributions received from others',
       onGoing: 'Ongoing',
       confirm: 'Confirm',
       completed: 'Completed',
       shortPaid: 'Short Paid',
       paymentStatus: 'Payment Status',
       confirmSendingPayment: 'Confirm Sending Payment to the Beneficiary.',
       messageWithStart: 'Message*',
       requestPayment: 'Request Payment',
       pleaseSelectAnyWithStar: 'Please select anyone option*',
       paymentStatusData: [
            {
               title1: 'No Payment',
               title2: 'Received',
            },
            {
               title1: 'Payment',
               title2: 'Completed',
            },
            {
               title1: 'Short',
               title2: 'Payment',
            },
       ]

    },
    groupInvitation: {
       groupInvitation: 'Group Invitation',
       accept: 'Accept',
       reject: 'Reject',
       viewDetails: 'View Details',
       saveMoney: 'Saving Money',
       youHaveNot: `You haven't received`,
       invitationYet: 'any invitations yet!',
    }

      
  },
  menu: {
    menu: 'Menu',
    menuList: [
      {
        title: 'Fund Groups',
        img: '',
        navigationKey: 'Home',
      },
      {
        title: 'Fund Raising Requests',
        img: '',
        navigationKey: 'Home',
      },
      {
        title: 'Settings',
        img: '',
        navigationKey: 'Settings',
      },
    ],
  },
  settings: {
    settings: 'Settings',
    logout: 'Sign out',
    shareApp: 'Share App',
    rateApp: 'Rate App',
    shareMesage: 'Wealth Concert',
    manageNotification: 'Manage Notifications',
    settingsList: [
      {
        title: 'My Profile',
        img: '',
        navigationKey: 'ViewProfile',
      },
      {
        title: 'Change Password',
        img: '',
        navigationKey: 'ChangePassword',
      },
      {
        title: 'Manage Notifications',
        img: '',
        navigationKey: '',
      },
      {
        title: 'Contact Us',
        img: '',
        navigationKey: 'ContactUs',
      },
      {
        title: 'Terms of Use',
        img: '',
        navigationKey: 'StaticContents',
      },
      {
        title: 'Privacy Policy',
        img: '',
        navigationKey: 'StaticContents',
      },
      {
        title: 'Rate App',
        img: '',
        navigationKey: 'Settings',
      },
      {
        title: 'Share App',
        img: '',
        navigationKey: 'Settings',
      },
      {
        title: '',
        img: '',
        navigationKey: 'Settings',
      },
      {
        title: '',
        img: '',
        navigationKey: 'Settings',
      },
      {
        title: 'Sign out',
        img: '',
        navigationKey: 'Settings',
      },
    ],
  },
  profile: {
    myProfile: 'My Profile',
    memberProfile: 'Member Profile',
    addPicture: 'Add Picture',
    maximumUploadFileSize: 'Maximum upload file size is 5MB',
    editProfile: 'Edit Profile',
    changePicture: 'Change Picture',
    notVerified: 'Not Verified',
    verified: 'Verified',
    changeEmailAddress: 'Change Email Address',
    newEmailAddress: 'New Email Address',
    enterNewEmailAddress: 'Enter your new email address',
    changeMobileNo: 'Change Mobile Number',
    newMobileNo: 'New Mobile Number',
    enterNewMobileNo: 'Enter your new mobile number',
    success: 'Successfully saved!',
    yourEmailAddressChangedSuccussfully:
      'Your email address has been changed successfully.',
    yourMobileNoChangedSuccussfully:
      'Your mobile number has been changed successfully.',
  },
  changePassword: {
    changePassword: 'Change Password',
    toChangeYourPassord:
      'To change your password, please complete the fields below:',
    oldPassword: 'Old password',
    enterYourOldPassword: 'Enter your old password',
    enterNewPassword: 'Enter your new password',
    confirmPassword: 'Confirm password',
    enterYourConfirmPassword: 'Confirm your password',
  },
  contact: {
    contact: 'Contact',
    enquiryTitle: 'Inquiry Title*',
    selectEnquiryTitle: 'Select inquiry title',
    success: 'Success!',
    yourMessageSent:
      'Your message has been sent to the administrator successfully. Please allow 24-48 hours for us to respond to your request.',
    constactUsData: [
      {countryName: 'Join a group'},
      {countryName: 'Leave a group'},
      {countryName: 'Create a group'},
      {countryName: 'Delete a group'},
    ],
    message: 'Message',
    maxLength: 'Maximum of 400 characters allowed',
    titleShouldNotBeEmpty: 'Title is a required field',
    messageShouldNotBeEmpty: 'Message is a required field.',
    pleaseSelectAnyOneOption: 'Please select one of the options.'
  },
  staticContents: {
    termsOfUse: 'Terms of Use',
  },
  verifyMobile: {
    verifyMobile: 'Verify Mobile Number',
    yourMobileNoVerified: 'Your mobile number has been verified successfully',
    mobileVerified: 'Mobile Verified!',
  },
  selectImageModal: {
    addPhoto: 'Add Photo!',
    takePhoto: 'Take Photo',
    chooseFromGallery: ' Choose from Gallery',
    cancel: 'Cancel',
  },
  createFundGroup: {
    groupTitle: 'Group Title*',
    fundRaisingTitle: 'Fund Raising Title*',
    fundRaisingDescription: 'Fund Raising Description*',
    groupTitleWithOutStart: 'Group Title',
    enterGroupTitle: 'Enter group title',
    groupDescription: 'Group Description*',
    entergroupDescription: 'Enter group description',
    maxCharacterAllowed: 'Message must contain 20-400 characters.',
    cyclePeriod: 'Cycle Period*',
    dateFormate: 'MM/DD/YYYY',
    startDate: 'Start Date',
    finishDate: 'Finish Date',
    selectStart: 'Select start date',
    selectFinish: 'Select finish date',
    currency: 'Currency*',
    amountToBePaid: 'Amount to be Paid by Each Member*',
    activePeriod: 'Active Period*',
    paymentType: 'Payment Period Type*',
    paymentTypeWithoutStart: 'Payment Period Type',
    weekly: 'Weekly',
    biWeekly: 'Bi-weekly',
    monthly: 'Monthly',
    dueDateBasedOnPaymentPeriod: 'Due Date*',
    deadLineDateBasedOnPaymentPeriod:
      'Deadline Date*',
    dueDay: 'Due Day',
    dueDate: 'Due Date',
    selectDueDate: 'Select Due Date',
    deadlineDay: 'Deadline Day',
    deadlineDate: 'Deadline Date',
    selectDeadLineDate: 'Select Deadline Date',
    numberOfMembers: 'Number of Members*',
    addGroupMembers: 'Add Group Members*',
    addGroupMembersFromOptions: 'Add members to this group.',
    addFromExistingGroup: 'Add from Existing Group Users',
    addFromPhoneContacts: 'Add from Phone Contacts',
    enterMemberNumber: 'Enter Mobile Number',
    totalFiveMembers: 'Maximum group size is 5 members',
    addGroupMembersFromFollowingOptions: 'Add members to this group.',
    addFromExisting: 'Add from Existing Group Users',
    addFromPhone: 'Add from Phone Contacts',
    enterMember: 'Enter Mobile Number',
    total: 'Total',
    member: 'Members',
    selectDay: 'Select day',
    thankYou: 'Thank You!',
    yourBuildingCreditGroup: 'Your Building Credit Group has been successfully created.',
    yourRequestIsSentToAll: 'Your request has been sent to all group members. You can track the status in the Fund Groups tab.',
    canNotAddMoreThanFive: 'You cannot add more than 5 members',
    your: 'Your',
    groupHasBeenCreatedSuccessfully: 'Group has been successfully created.',
    fundRaisingRequestHasBeenCreatedSuccessfully: 'Fund Raising Request has been successfully created.',
    existingGroupUsers:'Existing Group Member Contacts',
    phoneBookContactList: 'Phone Book Contacts List',
    selectContactsFromExistingGroup: 'Select Contacts from your Existing Group Members',
    selectContactsFromOurPhoneBook: 'Select Contacts from your Phone Book',
    noUsersFound: 'User not found.',
    close: 'Close',
    groupTitleQMarkInfo: 'Group Title is the name of the funds distribution group.',
    groupDescriptionQMarkInfo: 'Group Description describes the purpose of the group.',
    cyclePeriodQMarkInfo: 'Cycle Period represents the overall start and end date of the group lifecycle. It is the planning, execution and closing phases of the group.',
    activePeriodQMarkInfo: 'Active Period represents the Execution and closing phases of the group. It describes the period after the group is activated. This is when all invitees have either accepted or rejected the invitation, disbursement arrangements have been determined, and the group is ready to begin contributing to the first beneficiary',
    makeSureCountryCodeMustBeFilled: 'Country code must be filled out for all members.',
    checkBoxData: [
      {
        title: 'Weekly'
      },
      {
        title: 'Bi-weekly'
      },
      {
        title: 'Monthly'
      },
    ],
    daysData: [
      {
        countryName: 'Sunday',
      },
      {
        countryName: 'Monday',
      },
      {
        countryName: 'Tuesday',
      },
      {
        countryName: 'Wednesday',
      },
      {
        countryName: 'Thursday',
      },
      {
        countryName: 'Friday',
      },
      {
        countryName: 'Saturday',
      },
    ],
    currencyData: [
      {
        countryName: 'INR',
      },
      {
        countryName: 'USD',
      },
      {
        countryName: 'Cent',
      },
    ]
  },
  fieldPlaceHolder: {
      enterAmount: 'Enter amount',
      selectCurrency: 'Currency',
      enterNumberOfMembers: 'Enter number of members (e.g., 2-20)',
      selectDueDay: 'Due Day',
      selectDeadLineDay: 'Deadline Day',
      selectBeneficiaryName: 'Select unpaid member’s name',
      pleaseSelectBeneficiaryName: 'Please select unpaid member’s name',
  },
  fieldValidationErrorMessage: {
    groupTitleShouldNotBeEmpty: 'Group Title is a required field.',
    groupDescriptionShouldNotBeEmpty: 'Group Description is a required field.',
    groupsDescriptionBetween: 'Group Description must contain 20-400 characters.',
    amountShouldNotBeEmpty: 'Amount is a required field.',
    amountCannotContain: 'Amount cannot contain zero or negative value.',
    selectStartDate: 'Select start date.',
    selectFinishDate: 'Select end date.',
    selectCurrency: 'Select currency.',
    selectDueDay: 'Select due day.',
    selectDueDate: 'Select due date.',
    selectDeadLineDay: 'Select deadline day.',
    selectDeadLineDate: 'Select deadline date.',
    pleaseSelectReccurenceType: 'Please select payment type.',
    membersShoulNotBeEmpty: 'Members field should not be empty.',
    membersShouldBeGreaterThanTwo: 'Group must contain 2-20 members.',
    groupMembersShouldNotBeEmpty: 'Group members cannot be empty.',
    groupMembersShouldAtleast: 'Group members must be at least 2.',
    youCannotAddMoreThanTwentyMembers: `You cannot add more than 20 members in a group.`,
    youCannotAddMoreMembers: `You cannot add more members than the number you have entered`,
    numberOfMembersNAddedMembersMustBeEqual: 'Number of members and added members must be equal.',
    mobileNoAlreadyAdded: 'This mobile number has already been invited to the group.',
    passwordCannotBeBlank: `Password is a required field.`,
    cyclePeriodDateInSuchAwayThat: 'It is recommended that the cycle period be at least 14 days.',
    activePeriodStartDate: 'Active period start date should occur after or on cycle period start date.',
    dueDateShouldBe: 'Due date should occur after the active period start date and before deadline date.',
    deadLineDateShuoldBe: 'Deadline date should occur after due date and within the contribution cycle.',
    imageNotUploadedOnS3: 'Image not uploaded on bucket.',
  },
  noInternet: {
    oops: 'Oops!',
    thereIsNoInternetConnection: 'There is no Internet connection. Please check your internet connection.',
    tryAgain: 'Try again'
  },
  raisingRequest: {
     anyRequestYet : 'any requests yet!'
  },
  notification: {
     notification: 'Notifications'
  },
  appUpdate: {
    pleaseUpdateApp: 'Please Update App!',
    updateDescriptions: 'This update contains many more new features!',
    updateButtonTitle: 'Click to Update'

  },
  calender: {
     cancel: 'Cancel',
     done: 'Done'
  },
};

// Data Dictionary for the “?”
// Group Title: Group Title is the name of the fund distribution group.
// Group Description: Group Description describes the purpose of the group
// Cycle Period: Cycle Period represents the overall start and end date of the group lifecycle. It is the planning, execution and closing phases of the group
// Active Period: Active Period only represents the execution and closing phases of the group lifecycle. It describes the period after planning. This is when all invitees have either accepted or rejected the invitation, disbursement arrangements have been determined, the group has been activated, and members are ready to begin contributing to the first beneficiary.
// Due Date: Due Date describes the date a member’s payment is expected to be received by another member. 
// Deadline Date: Deadline Date describes the final day a member’s payment is expected to be received by another member.

